services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: chatbot
      POSTGRES_PASSWORD: chatbot_password
      POSTGRES_DB: chatbot_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-databases.sql:/docker-entrypoint-initdb.d/00-init-databases.sql
      - ./chatbot/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./scripts/add_memories.sql:/docker-entrypoint-initdb.d/02-memories.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatbot -d chatbot_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      CHAT_DATABASE_URL: postgresql://chatbot:chatbot_password@postgres:5432/chatbot_db
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      HYREX_DATABASE_URL: postgresql://chatbot:chatbot_password@postgres:5432/hyrex
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./frontend:/app/frontend:ro

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      CHAT_DATABASE_URL: postgresql://chatbot:chatbot_password@postgres:5432/chatbot_db
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      HYREX_DATABASE_URL: postgresql://chatbot:chatbot_password@postgres:5432/hyrex
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: